# Dimentions

In [ ]:
# N_D_Array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

In [6]:
# Use a tuple to create a NumPy array:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)


[1 2 3 4 5]


In [22]:
# 0D Araay
import numpy as np
arr=np.array(11)
print(arr)

print("Dimensions: ",arr.ndim)

11
Dimensions:  0


In [29]:
# One-D Array 
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)
print("Dimensions: ", arr.ndim)

[1 2 3 4 5]
Dimensions:  1


In [28]:
# 2-D Array
import numpy as np
arr=np.array([[1,2,3,4,5],[2,4,6,8,10]])
print(arr)
print("Dimensions: ",arr.ndim)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Dimensions:  2


In [33]:
# 3-D Array 
import numpy as np 
arr=np.array([[[1,2,3,4,5],[2,4,6,8,10],[1,3,5,7,9]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 2  4  6  8 10]
  [ 1  3  5  7  9]]]
3


# Array Indexing

In [95]:
# get first element
import numpy as np 
arr=np.array([1,2,4,5])
print(arr[0])

1


In [39]:
# get second element
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [46]:
#get element on 3rd and 4rth positon
import numpy as np 
arr= np.array([1,2,3,4,5])
print("Element on third position",arr[2])
print("Element on fourt position",arr[3])

Element on third position 3
Element on fourt position 4


In [52]:
#get second element from 1st row
import numpy as np
arr=np.array([[2,4,6,8],[1,3,5,7]])
print(arr)
print("2nd element on 1st row is:  ",arr[0][1])

[[2 4 6 8]
 [1 3 5 7]]
2nd element on 1st row is:   4


In [60]:
#5th element on the second row
import numpy as np 
arr=np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(arr)
print("5th element on the 2nd position is: ", arr[1][4])
print("Second way of printing: ", arr[1,4])

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]
5th element on the 2nd position is:  9
Second way of printing:  9


In [65]:
# 3-D array 
# access 3rd element of the second array of the first array 
import numpy as np 
arr=np.array([[[1,2,3],[4,5,6]],[[2,4,6],[1,3,5]]])
print(arr[0,1,2])

6


In [68]:
#Print Last Element Of the one 1-D array
import numpy as np
arr= np.array([[1,2,3],[2,4,6]])
print("Last Elenment of the 1-D",arr[1,-1])

Last Elenment of the 1-D 6


# Slicing

In [75]:
# start from index 0 to 4 and it takes one step by each element
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[0:4:1])

[1 2 3 4]


In [76]:
# start from index 0 to 4 and it takes two step by each element
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[0:4:2])

[1 3]


In [77]:
#it Start form 0 index and ends on 4 index
import numpy as np
arr=np.array([2,4,6,8])
print(arr[0:4])

[2 4 6 8]


In [78]:
# Slice element form 3 index end of the array
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[3:])

[4 5]


In [82]:
#Slice element form 0 index to 3(not included)
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[:3])

[1 2 3]


In [91]:
#Slice element form -5 to end 
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[-5:])

[1 2 3 4 5]


In [94]:
#Slice element form index -5 to end before index -1
import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[-5:-1])

[3 4 5 6]


# Operations

In [98]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [100]:
print(arr.ndim)

2


In [105]:
import numpy as np
A=np.array([[1,2,],
            [2,4]])
B=np.array([[3,4],
            [6,8]])
print(A+B)

[[ 4  6]
 [ 8 12]]


In [109]:
print(A.shape,B.shape)

(2, 2) (2, 2)


In [110]:
print(np.dot(A,B))

[[15 20]
 [30 40]]


In [111]:
print(A@B)

[[15 20]
 [30 40]]


In [112]:
A-B

array([[-2, -2],
       [-4, -4]])