In [3]:
# N_D_Array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Use a tuple to create a NumPy array:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)


[1 2 3 4 5]


In [22]:
# 0D Araay
import numpy as np
arr=np.array(11)
print(arr)

print("Dimensions: ",arr.ndim)

11
Dimensions:  0


In [29]:
# One-D Array 
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)
print("Dimensions: ", arr.ndim)

[1 2 3 4 5]
Dimensions:  1


In [28]:
# 2-D Array
import numpy as np
arr=np.array([[1,2,3,4,5],[2,4,6,8,10]])
print(arr)
print("Dimensions: ",arr.ndim)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Dimensions:  2
