In [3]:
# N_D_Array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# Use a tuple to create a NumPy array:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)


[1 2 3 4 5]


In [22]:
# 0D Araay
import numpy as np
arr=np.array(11)
print(arr)

print("Dimensions: ",arr.ndim)

11
Dimensions:  0


In [29]:
# One-D Array 
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)
print("Dimensions: ", arr.ndim)

[1 2 3 4 5]
Dimensions:  1


In [28]:
# 2-D Array
import numpy as np
arr=np.array([[1,2,3,4,5],[2,4,6,8,10]])
print(arr)
print("Dimensions: ",arr.ndim)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Dimensions:  2


In [33]:
# 3-D Array 
import numpy as np 
arr=np.array([[[1,2,3,4,5],[2,4,6,8,10],[1,3,5,7,9]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3  4  5]
  [ 2  4  6  8 10]
  [ 1  3  5  7  9]]]
3


In [37]:
# Array Indexing
# get first element
import numpy as np 
arr=np.array([1,2,4,5])
print(arr[0])

1


In [39]:
# get second element
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [46]:
#get element on 3rd and 4rth positon
import numpy as np 
arr= np.array([1,2,3,4,5])
print("Element on third position",arr[2])
print("Element on fourt position",arr[3])

Element on third position 3
Element on fourt position 4


In [52]:
#get second element from 1st row
import numpy as np
arr=np.array([[2,4,6,8],[1,3,5,7]])
print(arr)
print("2nd element on 1st row is:  ",arr[0][1])

[[2 4 6 8]
 [1 3 5 7]]
2nd element on 1st row is:   4


In [60]:
#5th element on the second row
import numpy as np 
arr=np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(arr)
print("5th element on the 2nd position is: ", arr[1][4])
print("Second way of printing: ", arr[1,4])

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]
5th element on the 2nd position is:  9
Second way of printing:  9


In [65]:
# 3-D array 
# access 3rd element of the second array of the first array 
import numpy as np 
arr=np.array([[[1,2,3],[4,5,6]],[[2,4,6],[1,3,5]]])
print(arr[0,1,2])

6


In [68]:
#Print Last Element Of the one 1-D array
import numpy as np
arr= np.array([[1,2,3],[2,4,6]])
print("Last Elenment of the 1-D",arr[1,-1])

Last Elenment of the 1-D 6


In [70]:
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[0:4:1])

[1 2 3 4]


In [72]:
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr[0:4:2])

[1 3]
